module.exports = {
  content: [
    './config/*.json',
    './layout/*.liquid',
    './assets/*.liquid',
    './sections/*.liquid',
    './snippets/*.liquid',
    './templates/*.liquid',
    './templates/*.json',
    './templates/customers/*.liquid',
  ],
  theme: {
    fluidSpacing: {
      tiny: 'var(--size-tiny)',
      xxs: 'var(--size-xxs)',
      xs: 'var(--size-xs)',
      sm: 'var(--size-sm)',
      100: 'var(--size-100)',
      200: 'var(--size-200)',
      250: 'calc(var(--size-200) + 1px)',
      300: 'var(--size-300)',
      350: 'calc(var(--size-300) + 1.5px)',
      400: 'var(--size-400)',
      450: 'calc(var(--size-400) + 2px)',
      500: 'var(--size-500)',
      550: 'calc(var(--size-500) * 1.15)',
      600: 'var(--size-600)',
      650: 'calc(var(--size-600) * 1.15)',
      700: 'var(--size-700)',
      750: 'calc(var(--size-700) * 1.2)',
      800: 'var(--size-800)',
      850: 'calc(var(--size-800) * 1.2)',
      900: 'var(--size-900)',
      950: 'calc(var(--size-900) * 1.2)',
      lg: 'var(--size-lg)',
      xl: 'var(--size-xl)',
      xxl: 'var(--size-xxl)',
      huge: 'var(--size-huge)',
      gutter: 'var(--gutter)',
      container: 'var(--container-padding)',
    },
    extend: {
      padding: (theme) => theme('fluidSpacing'),
      margin: (theme) => theme('fluidSpacing'),
      spacing: (theme) => theme('fluidSpacing'),
      gap: (theme) => theme('fluidSpacing'),
      fontSize: (theme) => theme('fluidSpacing'),
      flexGrow: {
        9: '9999',
      },
      lineHeight: {
        flat: '1.1',
      },
      colors: {
        'primary-glare': '#EAE1D6',
        'primary': '#FFC356',
        'primary-shade': '#C6802A',
        'dark-glare': '#262522',
        'dark': '#1C1B17',
        'dark-shade': '#191817',
        'light-glare': '#ffffff',
        'light': '#fafafa',
        'light-shade': '#F3F2E7',
        'black': '#000000',
        'white': '#FFFFFF',
      },
      fontFamily: {
        base: ['Jost', 'Helvetica', 'Arial', 'Lucida', 'sans-serif'],
        heading: ['Jost', 'Helvetica', 'Arial', 'Lucida', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
